apiVersion: apps/v1
kind: Deployment
metadata:
  name: resource-api
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resource-api
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  template:
    metadata:
      labels:
         app: resource-api
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: project
                operator: In
                values:
                - resource-api
      containers:
      - env:
        - name: TZ
          value: Asia/Shanghai
        - name: POD_OWN_IP_ADDRESS
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        image: swr.cn-east-2.myhuaweicloud.com/basis/resource-api:v20-owner
        imagePullPolicy: Always
        name: resource-api
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: {}
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
        volumeMounts:
        - mountPath: /etc/localtime
          name: vol1
        - mountPath: /config
          name: config
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      tolerations:
      - effect: NoExecute
        key: node.kubernetes.io/unreachable
        operator: Exists
        tolerationSeconds: 2
      - effect: NoExecute
        key: node.kubernetes.io/not-ready
        operator: Exists
        tolerationSeconds: 2
      volumes:
      - hostPath:
          path: /etc/localtime
        name: vol1
      - hostPath:
          path: /config
        name: config
